### ISSUE TITLE
Ip blocked by Binance

### ISSUE THREAD

**Issue by ret3030** [waxdred/Binance-Trader-Bot#4]
Hello, is there any way how to adjust delay between every api request? When using multiple ids Binance block ip adress. 

Thank you

**Comment by waxdred** [comment]
You can use the 'delai' parameter in the config/config.json file to adjust the delay between API requests. If I recall correctly, the delay was set to around 20 pings per minute.

**Comment by ret3030** [comment]
Thank you waxdred for responding. I dont know what am I doing wrong but terminal always hangs after few minutes no matter how I change the .await delay or the config value.

**Comment by waxdred** [comment]
I hope they haven't enhanced security to ban people for excessive ping. A few months ago, they simply issued a 2-minute ban.

**Comment by ret3030** [comment]
It looks like they heavily limited api pings. My idea was to create delay between every leaderboard scrape. But not sure if its possible. If you have multiple (lets say 5) traders at once, the request is automatically blocked in few secconds and your IP is banned for like 10minutes.

Thank you

**Comment by waxdred** [comment]
Yes, it's possible. You would need to implement multi-threading and modify the code's design a bit. I can take care of it within the week.

**Comment by ret3030** [comment]
That would be awesome, the multi-threading idea is quite the soulotion that the bot needs.

Thank you
