### ISSUE TITLE
Webhooks not sending to the channel

### ISSUE THREAD

**Issue by NishooYT** [waxdred/Binance-Trader-Bot#5]
I am trying out the code you provided I've installed everything and did setup the config with some uids and  the webhook and when I run the code with ( make ) or ( make run ) I could se the requests to binance is successful and the positions in consol but nothing is sent to the discord server pls help!

**Comment by waxdred** [comment]
Hi,
You are sur the url of your webhook discord is correct?

**Comment by NishooYT** [comment]
Yes

tors 14 sep. 2023 kl. 21:26 skrev jmilhas ***@***.***>:

**Comment by waxdred** [comment]
you can contact me on my discord for see you config if you want
waxcoin#1624
